# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/download_test/synthesized_ip/prgrom/inst_ram.coe
add_files c:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/download_test/synthesized_ip/dram/data_ram.coe
add_files -quiet C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/download_test/synthesized_ip/dram/dram.dcp
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/download_test/synthesized_ip/dram/dram.dcp]
add_files -quiet C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/download_test/synthesized_ip/prgrom/prgrom.dcp
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/download_test/synthesized_ip/prgrom/prgrom.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/ALU.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/CPU.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/CTRL_Unit.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/Ctrl_Hazard_Detector.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/DRAM.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/Data_Hazard_Detector.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/EXE_MEM_Regs.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/ID_EXE_Regs.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/IF_ID_Regs.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/IROM.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/ImmGenerator.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/MEM_WB_Regs.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/NPC.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/PC.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/PCsel_selected.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/RF.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/Top_PC.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/display.v
  C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/new/top_display.v
}
read_ip -quiet C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/constrs_1/new/cpu_cstr.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/CPU_SingleCycle/CPU_SingleCycle/CPU_SingleCycle.srcs/constrs_1/new/cpu_cstr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CPU_top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_top_utilization_synth.rpt -pb CPU_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
